//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatternLibrary.GumballMachineService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GumballMachineService.IGumballMachineService")]
    public interface IGumballMachineService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGumballMachineService/GetStatus", ReplyAction="http://tempuri.org/IGumballMachineService/GetStatusResponse")]
        string GetStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGumballMachineService/GetGumball", ReplyAction="http://tempuri.org/IGumballMachineService/GetGumballResponse")]
        void GetGumball();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGumballMachineServiceChannel : PatternLibrary.GumballMachineService.IGumballMachineService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GumballMachineServiceClient : System.ServiceModel.ClientBase<PatternLibrary.GumballMachineService.IGumballMachineService>, PatternLibrary.GumballMachineService.IGumballMachineService {
        
        public GumballMachineServiceClient() {
        }
        
        public GumballMachineServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GumballMachineServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GumballMachineServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GumballMachineServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetStatus() {
            return base.Channel.GetStatus();
        }
        
        public void GetGumball() {
            base.Channel.GetGumball();
        }
    }
}
